library(fredr)
library(tidyverse)
library(magrittr)
library(patchwork)
library(lubridate)
library(tsibble)
library(feasts)
library(forecast)
library(sandwich)
library(lmtest)
library(nycflights13)
library(blsR)
library(fable)
library(quantmod)

set.seed(898)
ar1.1 <- arima.sim(n = 100, list(ar = c(0.4)))
set.seed(898)
ar1.2 <- arima.sim(n = 100, list(ar = c(0.8)))
set.seed(898)
ar1.3 <- arima.sim(n = 100, list(ar = c(0.9)))
set.seed(898)
arma21 <- arima.sim(n = 100, list(ar = c(0.6, 0.3), ma = c(0.5)))


